[global]
    server string = samba
    idmap config * : range = 3000-7999
    security = user
    server min protocol = SMB2

    # disable printing services
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

    host msdfs = no
    wide links = yes
    follow symlinks = yes
    unix extensions = no
    acl allow execute always = yes

    # allow SMB clients to read/write extended attributes (xattrs) on files
    # enabled to support vfs_streams_xattr
    ea support = yes

    # MacOS Compatibility options
    vfs objects = catia fruit streams_xattr
	fruit:resource = file
	fruit:metadata = stream
	fruit:locking = netatalk
	fruit:encoding = native

    # Special configuration for Apple's Time Machine
    fruit:model = TimeCapsule
    fruit:aapl = yes

    # fix filenames with special chars (should be default)
    mangled names = no
    dos charset = CP850
    unix charset = UTF-8

[Data]
    path = /storage
    comment = Shared
    browseable = yes
    writable = yes
    read only = no
